chassis:    
    lf_vel_controller:
        type: "effort_controllers/JointVelocityController"
        joint: left_front_wheel_joint
        pid: {p: 100, i: 0.01, d: 10.0}
    lb_vel_controller:
        type: "effort_controllers/JointVelocityController"
        joint: left_back_wheel_joint
        pid: {p: 100, i: 0.01, d: 10.0}
    rf_vel_controller:
        type: "effort_controllers/JointVelocityController"
        joint: right_front_wheel_joint
        pid: {p: 100, i: 0.01, d: 10.0}
    rb_vel_controller:
        type: "effort_controllers/JointVelocityController"
        joint: right_back_wheel_joint
        pid: {p: 100, i: 0.01, d: 10.0}
