joint_state_controller:
    type: "joint_state_controller/JointStateController"
    publish_rate: 300
arm:
    arm_joint_controller:
        type: "effort_controllers/JointTrajectoryController"
        joints:
            - joint1
            - joint2
            - joint3
        gains:
            joint1: { p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0 }
            joint2: { p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0 }
            joint3: { p: 1000, i: 0.0, d: 0.1, i_clamp: 0.0 }
