bus:
  - can0
loop_frequency: 1000
cycle_time_error_threshold: 0.001
thread_priority: 30

actuators:
  joint1_motor:
    bus: can0
    id: 0x001
    type: DM_J4310
  joint2_motor:
    bus: can0
    id: 0x141
    type: MG_8016
  joint3_motor:
    bus: can0
    id: 0x142
    type: MG_8016
