controller_list:
  - name: fake_engineer_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
<<<<<<< Updated upstream:sp_control/engineer_manipulator_moveit_config/config/fake_controllers.yaml
      - joint4
      - joint5
      - joint6
      - joint7
initial:  # Define initial robot poses per group
  - group: engineer_manipulator
    pose: home
=======
initial: # Define initial robot poses per group
  - group: arm
    pose: Home
>>>>>>> Stashed changes:sp_control/engineer2_manipulator_moveit_config/config/fake_controllers.yaml
